apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - db-credentials.yaml
  - migration.yaml

images:
  - name: vid2vec
    newName: placeholder.registry/vid2vec
    newTag: latest
