apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vid2vec-api-ingress
  labels:
    app: vid2vec-api
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: "<ACM_CERTIFICATE_ARN>"
spec:
  tls:
    - hosts:
        - "<DOMAIN_NAME>"
      secretName: vid2vec-api-tls
  rules:
    - host: "<DOMAIN_NAME>"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vid2vec-api-service
                port:
                  number: 8080
