apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api.yaml
  - workers.yaml
  - hpa.yaml
  - ingress.yaml

images:
  - name: vid2vec
    newName: placeholder.registry/vid2vec
    newTag: latest
